appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bOfb65Vl8t8Tw6zhbDDOTgsAIxV5NKifepYR1sAqWqeLQM46TgU3VATrzQUijGIFgz4LtcXle/T9tlpHLpbgHvfFbLJ5TlTEeES/kLbF6AV8NWIp6qA4nR9gBW4ob6A27am7e3mv1H+tWy5w9PnGcbNwDC8AdHuNAZ82IhlZPlTyZn6EYTsN26r3bDPTsVhHre4J1bv5AM6Iks7x4kkON3FxpoT3rGMrsCHpKo8dpH805jxiLjvn4n9blyStWbSB66VSpiekk8+BVw0cFPCPA+1vO8fXsCD+/YFWhZ5Kb7xp3K3BXGa/cPGzsEE3fOq0K2eNrs+ExUEqWQPAWCs8YWVbLA/ZTR07kdTX7GSXqjFo8vLNUH0CMGEzOxC4IDg/t/N7CUWF0jvyk8my0y6ATWS21uFo/ig2zTveSIOKXHd4buIsxTIwAAs0Bt/ZLGbUPjKoMITDWQmWV0RfHK9mgC9JIxJB2xe/fy/6piGHWXrwl4sBvw1XAsRS7gkSp7srRcoLTWooN+Mr7svGo4SD0iDtamHYNMmOkZ6pUq4X0vviEGeDV4R9rYKStax5LuKGH+gRdUdLThIFtqhmQDazKVoCXbvn5cHQWRDrz92WFfPsICmXV5/lxYtVNiwlcVRad5e1eIop5LtvpPXIRF/iYkISwqpyaOrWGP/lNITUj2k=}
